### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3]], which is output 0 of CumprodBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by railgun-zyy** [ziplab/SPViT#1] opened 2023-06-12 06:41 UTC
I don't know how to solve, please tell me:
Traceback (most recent call last):
  File "main_pruning.py", line 441, in <module>
    main()
  File "main_pruning.py", line 363, in main
    train_stats, str_threshold_indicators = train_one_epoch_pruning(
  File "/home/lz/zyy/SPViT-master/SPViT_DeiT/engine.py", line 118, in train_one_epoch_pruning
    loss_scaler(loss, optimizer1, optimizer2, clip_grad=max_norm, create_graph=is_second_order1, model=model)
  File "/home/lz/zyy/SPViT-master/SPViT_DeiT/utils.py", line 410, in __call__
    self._scaler.scale(loss).backward(create_graph=create_graph)
  File "/home/lz/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/lz/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3]], which is output 0 of CumprodBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "main_pruning.py", line 441, in <module>
    main()
  File "main_pruning.py", line 363, in main
    train_stats, str_threshold_indicators = train_one_epoch_pruning(
  File "/home/lz/zyy/SPViT-master/SPViT_DeiT/engine.py", line 118, in train_one_epoch_pruning
    loss_scaler(loss, optimizer1, optimizer2, clip_grad=max_norm, create_graph=is_second_order1, model=model)
  File "/home/lz/zyy/SPViT-master/SPViT_DeiT/utils.py", line 410, in __call__
    self._scaler.scale(loss).backward(create_graph=create_graph)
  File "/home/lz/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/lz/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3]], which is output 0 of CumprodBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by Charleshhy** [comment] 2023-09-12 06:55
Hi railgun-zyy,

Thanks for your interest in our project. I cannot reproduce this error. Can you tell me what command that you used led to this issue?

Kind regards,
Haoyu

**Comment by Charleshhy** [comment] 2024-01-15 02:47
Close this issue as it has no further activity.

**Closed as completed by Charleshhy** 2024-01-15 02:47 UTC
